services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - db:\data\db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: store-zero

volumes:
  db: