name: Secret Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          curl -sSfL https://github.com/zricethezav/gitleaks/releases/download/v8.2.0/gitleaks_8.2.0_linux_x64.tar.gz | tar -xz -C /usr/local/bin gitleaks

      - name: Run Gitleaks
        run: gitleaks detect --source . --report-path gitleaks-report.json

#  trufflehog:
#    if: github.event_name == 'workflow_dispatch'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Install TruffleHog
#        run: |
#          pip install truffleHog
#
#      - name: Run TruffleHog
#        run: trufflehog git --repo-path . --json > trufflehog-report.json